# Generated by Django 2.2 on 2020-12-16 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('employeeNum', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=15)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('hobby', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.IntegerField(default=1)),
                ('phone', models.CharField(max_length=11)),
                ('motto', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=80, null=True)),
                ('salary', models.CharField(max_length=80, null=True)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ClassInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(blank=True, null=True)),
                ('wage', models.CharField(max_length=50)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserType'),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('explain', models.TextField(default='无', max_length=500)),
                ('state', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_leave', models.BooleanField(default=False)),
                ('detail', models.TextField(default='无')),
                ('leave_count', models.IntegerField(default=0)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo')),
            ],
        ),
    ]
